<!--libraries-->
<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular-route.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular-resource.js"></script>
{{--<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular-sanitize.js"></script>--}}
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular-touch.js"></script>
<script type="text/javascript" src="https://www.2checkout.com/checkout/api/2co.min.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>-->
<script src="<?php echo asset('js/lib/jquery.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/bootstrap.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular.js')?>"></script>
<script src="<?php echo asset('js/lib/angular-route.js')?>"></script>
<script src="<?php echo asset('js/lib/angular-resource.js')?>"></script>
<script src="<?php echo asset('js/lib/angular-touch.js')?>"></script>
<script src="<?php echo asset('js/lib/loader.js')?>"></script>
<script src="<?php echo asset('js/lib/angular/ui-bootstrap.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/ui-bootstrap-tpls.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/ui-sortable.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/angular-inview.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/request-factory.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/checklist-model.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/util.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/lightbox/angular-bootstrap-lightbox.js'); ?>"></script>
<script src="<?php echo asset('js/lib/jquery-ui.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/moment/min/moment-with-locales.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/moment/min/moment-timezone.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/moment/angular-moment.js'); ?>"></script>
<script src="<?php echo asset('js/lib/datetimepicker.js'); ?>"></script>
<script src="<?php echo asset('js/lib/datetimepicker.templates.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular-jwplayer/angular-jwplayer.js'); ?>"></script>
<script src="<?php echo asset('js/lib/jwplayer-mirror/jwplayer.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/videogular.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/buffering.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/controls.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/overlay-play.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular/ng-onload.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular-hotkeys/build/hotkeys.js'); ?>"></script>
<script src="<?php echo asset('js/lib/flow.js'); ?>"></script>
<script src="<?php echo asset('js/lib/ng-flow.js'); ?>"></script>
<script src="<?php echo asset('js/lib/datetimepicker.js'); ?>"></script>
<script src="<?php echo asset('js/lib/textAngular/textAngular.js'); ?>"></script>
<script src="<?php echo asset('js/lib/textAngular/textAngular-sanitize.js'); ?>"></script>
<script src="<?php echo asset('js/lib/textAngular/textAngularSetup.js'); ?>"></script>
<script src="<?php echo asset('js/lib/rangy/rangy-core.js'); ?>"></script>
<script src="<?php echo asset('js/lib/rangy/rangy-selectionsaverestore.js'); ?>"></script>
<script src="<?php echo asset('js/lib/FileSaver.js'); ?>"></script>
<script src="<?php echo asset('js/lib/angular-ui-calendar/src/calendar.js'); ?>"></script>
<script src="<?php echo asset('js/lib/fullcalendar/dist/fullcalendar.min.js'); ?>"></script>
<script src="<?php echo asset('js/lib/fullcalendar/dist/gcal.js'); ?>"></script>
<!--<script src="https://github.com/niklasvh/html2canvas/releases/download/0.4.1/html2canvas.js"></script>-->
<script src="<?php echo asset('js/lib/html2canvas.js'); ?>"></script>
<!--<script src="<?php echo asset('js/lib/stripe.js'); ?>"></script>-->
<script src="https://meet.jit.si/external_api.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular-cookies.js"></script>