<?php

return array(
  "terms-and-conditions" => "<h1>Términos y condiciones de OxoAwards</h1>
        <ol>
            <li><p><span><b>Definiciones y Características del Servicio. </b></span></p></li>
        </ol>
        <p><span>1.1. Oxobox Awards Services (En adelante Oxoawards) es un solución de software que facilita el intercambio de material entre un usuario participante, un organizador y el jurado de un festival de premiación.</span></p>
        <p><span>1.2. Los flujos de carga, manejo de datos y visualización a través de herramientas de voto quedan circunscriptos al grupo de usuarios que responde al organizador del festival, quien cuenta con todas las herramientas de gestión.</span></p>
        <p><span>1.3. La empresa Soluciones Oxo S.A. (en adelante Oxobox), administradora de Oxoawards, es ajena al uso de los datos que se publiquen y por esta razón son temas ajenos y no susceptibles de ser reclamados a Oxobox.</span></p>
        <p><span>1.4. Dependiendo del uso que efectivamente cada usuario realice de la plataforma Oxoawards, los mismos pueden ser clasificados en “participantes”, “organizadores”, o simplemente “público en general”.</span></p>
        <p ><span>1.5. Se entiende por participante al usuario que dispone de credenciales de registración que le permite presentarse a un festival convocante, con la finalidad de mostrar sus contenidos a efectos de ser ponderados.</span></p>
        <p><span>1.6 Se entiende por organizador al usuario que dispone de credenciales de registración que le permiten ser el administrador de un festival. El mismo se encarga de manejar fechas, criterios y condiciones de convocatoria. En caso de existir requerimientos de pago de admisión al participante de festival, este usuario organizador es el responsable inequívoco sobre la gestión comercial del festival. </span></p>
        <p><span>1.7 Público en general será aquellos usuarios que no disponen de credenciales de registración, por lo cual solo acceden en calidad de visualizador de aquellos contenidos que el organizador disponga para vista pública.</span></p>
        <br>
        <ol>
            <li><p><span><b>Condiciones del servicio.</b></span></p></li>
        </ol>
        <p><span>Los siguientes términos y condiciones regulan cualquier uso de Oxoawards y todo el contenido, servicios y productos disponibles dicho sistema.</span></p>
        <p><span>Lee este acuerdo detenidamente antes de acceder o utilizar Oxoawards. Al acceder o utilizar cualquier parte del Oxoawards, aceptas regirte por los términos y condiciones del presente acuerdo. Si no estás de acuerdo con todos los términos y condiciones del presente acuerdo, no podrás acceder a Oxoawards ni usar ninguno de los servicios. Si estos términos y condiciones se consideran una oferta de Oxobox, su aceptación está expresamente limitada a dichas condiciones.</span></p>
        <br>
        <p ><span>2.1. Oxobox, brinda su servicio de alojamiento de festivales de premiación para contenidos audiovisuales denominado Oxoawards, y nos encantaría que lo usaras. Oxobox y Oxoawards son servicios gratuitos para los usuarios participantes y público en general,</span><span> </span><span>independientemente de lo que cada festival sponsorizado &nbsp;-usuario organizador - decida cobrar por la participación en el mismo.</span></p>
        <p><span>2.2. Nuestro servicio está diseñado para ofrecerte tanto control y sentido de la propiedad sobre lo que ocurre con tu sitio como sea posible, así como para animarte a expresarte tal como eres con total libertad. Sin embargo, debes ser responsable de lo que publicas. En concreto, asegúrate de que ninguno de los elementos prohibidos (como es el caso de spam, virus o amenazas graves de violencia) aparezca en tu sitio y de que tu sitio no incluya ningún enlace a ellos.</span></p>
        <br>
        <p><span>2.3. Si encuentras un festival sobre Oxoawards que, en tu opinión, infringe las condiciones del servicio, visita nuestra página de informe y resolución de conflictos. </span><span>www.oxoawards.com/rules</a>)</span></p>
        <br>
        <p><span>2.4. Otorgando tu aceptación a los términos y condiciones, el sitio web se ofrece sin modificación de todos los términos y condiciones aquí citados y de todas las normas, políticas (incluidas, entre otras, la Política de Privacidad de Oxoawards </span><span>(</span><a href='https://www.oxoawards.com/#/privacypolicy' target='_blank'><span>www.oxoawards.com/#/privacypolicy)</span></a><span> y procedimientos de funcionamiento que Oxoawards pueda publicar cada cierto tiempo en este sitio (en su conjunto, el “acuerdo”). </span></p>
        <p><span>2.5. Al aceptar el acuerdo, estás haciéndolo con Oxobox.</span></p>
        <p><span>2.6. El sitio web no está dirigido a niños menores de 13 años y el servicio del sitio web solo se ofrece a usuarios mayores de 13 años. No debes registrarte para usar el sitio web si tienes menos de 13 años. Cualquier persona que se registre como usuario o que proporcione su información personal al sitio web declara que es mayor de 13 años.</span></p>
        <p><span>2.7. Tu cuenta de Oxoawards. </span></p>
        <ul>
            <li>Si creas una entrada en Oxoawards, también llamado Entry, serás el responsable de mantener la seguridad de tu cuenta; además, serás enteramente responsable de todas las actividades que se efectúen con esa cuenta y de cualquier otra acción que se lleve a cabo en relación con el Oxoawards. &nbsp;&nbsp;</span></p></li>
            <li>No debes describir ni asignar palabras clave a tu Entry</span><span> </span><span>de un modo ilegal, que conduzca a equívoco o que esté ideado para explotar el nombre o la reputación de terceros; asimismo, Oxobox podrá cambiar o eliminar cualquier descripción o palabra clave que considere inapropiada, ilegal o que, de otro modo, pueda causar perjuicios a terceros.</span></p></li>
            <li>Debes notificar inmediatamente a Oxobox </span><span>(</span>info@oxobox.tv<span> </span><span>cualquier uso no autorizado de tu cuenta, así como cualquier otra infracción de la seguridad. Oxobox no será responsable de ninguno de tus actos u omisiones, incluidos los daños y perjuicios de cualquier tipo derivados de dichos actos u omisiones.</span></p></li>
        </ul>
        <p>2.8. Responsabilidad de los usuarios de Oxoawards.</span></p>
        <ul>
            <li>Si gestionas un festival, realizas comentarios, publicas material en Oxoawards, publicas enlaces de Oxoawards en sitios web o, por otro lado, pones material a disposición pública (o permites a un tercero que lo haga) por medio de Oxoawards (este tipo de material se denomina “contenido”), serás enteramente responsable del contenido y de los posibles perjuicios que pueda ocasionar dicho contenido. Esto es independiente de la forma que adopte el contenido, lo que incluye, entre otros formatos, textos, fotografías, vídeos, audios o códigos. Al poner a disposición pública el contenido, declaras y garantizas que el contenido no infringe el presente acuerdo.</span></p></li>
            <li>Al enviar contenido a Oxoawards para incluirlo en tu perfil de usuario, concedes a Oxobox una licencia no exclusiva, exenta de derechos e internacional para reproducir, modificar, adaptar y publicar el contenido con el único propósito de mostrar, distribuir y promover tu contenido. Esta licencia permite a Oxobox poner el contenido publicado a disposición de terceros seleccionados por Oxobox para que dichos terceros puedan analizar y distribuir (pero no mostrar públicamente) este contenido a través de sus servicios.</span></p></li>
            <li>Si eliminas cualquier contenido, Oxobox utilizará todos los medios razonables para borrarlo del sitio web, pero reconoces que el almacenamiento en caché o las referencias al contenido no dejarán de estar disponibles de inmediato.</span></p></li>
            <li>Sin limitación de esas representaciones o garantías, Oxobox tiene derecho (pero no la obligación), a la entera discreción de Oxobox , a (i) rechazar o eliminar cualquier contenido que, en su opinión razonada, infrinja las políticas de Oxobox o que, de algún modo, sea perjudicial u objetable, o bien (ii) cancelar o denegar el acceso y el uso del sitio web a cualquier persona o entidad por algún motivo según el exclusivo criterio de Oxobox . Oxobox no tendrá la obligación de reembolsar ninguna cantidad previamente pagada.</span></p></li>
        </ul>
        <br>
        <ol>
            <li><span><b>Pagos y renovación. </b></span></p></li>
        </ol>
        <p>3.1. Condiciones generales. </span></p>
        <p>Como quedó determinado en el punto 2.1. del presente, Oxoawards es un servicio sin costo alguno para los usuarios participantes y público en general, sin perjuicio de lo que cada usuario organizador decida cobrar a los mismos.</span></p>
        <p>Oxobox no tiene vinculación alguna con las opciones de pago que cada usuario organizador incluya en su interfaz, y por lo tanto, es ajena a toda responsabilidad derivada de dicha operación, de su modificación y/o condiciones y/o cancelación.</span></p>
        <p>En el caso en que, siendo un usuario participante, pretendieras la cancelación al acceso al Festival en cualquier momento, e intentaras dicha cancelación haciendo uso de la interfaz Oxoawards, ésta únicamente hará el envío de una notificación de cortesía al organizador, no siendo Oxobox obligada ni responsable del resultado de la misma.</span></p>
        <p>De existir, los términos de reembolso son exclusiva potestad del organizador, &nbsp;y Oxobox no intermedia en la solución de conflictos que pudiera haber entre participantes y el organizador de un festival. </span></p>
        <br>
        <p><span>3.2. No obstante, si tu nivel de usuario es el de organizador, podrás encontrar disponibles servicios de pago opcionales, como pagos de inscripciones, el almacenamiento adicional o las compras de dominios (cualquiera de estos servicios se denomina “mejora”). Cuando seleccionas una mejora, aceptas pagar a Oxobox las tasas de suscripción mensuales o anuales indicadas para dicho servicio. Los pagos se cargarán mediante prepago el día que te registres para una mejora y cubrirán el uso de ese servicio durante un periodo de suscripción mensual o anual, según corresponda. No se reembolsarán las tasas correspondientes a la mejora.</span></p>
        <br>
        <ol>
            <li><b>Contenido. Uso restringido. </b></span></p></li>
        </ol>
        <p>4.1. No debes utilizar el Oxoawards para copiar sustancialmente productos o servicios ofrecidos por Oxobox, lo que incluye la republicación de contenido de Oxoawards . Si Oxobox creyese, a su entera discreción, que has infringido o intentado infringir las presentes condiciones o el espíritu de dichas condiciones, tu capacidad para usar y acceder al Oxoawards puede quedar revocada temporal o permanentemente, con o sin previo aviso.</span></p>
        <p>4.2. Responsabilidades de los visitantes del sitio web. Oxobox no ha revisado, ni puede revisar, todo el material, incluido el software informático, publicado en el sitio web; no puede, por tanto, ser responsable del contenido, el uso o los efectos de dicho material. Al gestionar el sitio web, Oxobox no declara ni insinúa que dé su respaldo al material publicado o que crea que dicho material es adecuado, útil o no perjudicial. Será responsabilidad tuya adoptar las precauciones necesarias para protegerte a ti mismo y a los sistemas de tu ordenador contra virus, gusanos, troyanos u otro contenido perjudicial o dañino. 4.3. El sitio web puede alojar contenido ofensivo, indecente o, de otro modo, objetable, así como contenido que incluya imprecisiones técnicas, errores tipográficos u otros fallos. También es posible que el sitio web contenga material que infrinja los derechos de privacidad o publicidad, o bien que incumpla los derechos de propiedad intelectual u otros derechos de propiedad de terceros; la descarga, copia o uso de dicho material puede estar asimismo sujetos a términos y condiciones adicionales, explícitos o no. Oxobox rechaza cualquier responsabilidad por los perjuicios resultantes del uso que hagan los usuarios del sitio web o de las descargas que realicen dichos visitantes del contenido publicado. </span></p>
        <p>4.4. Contenido publicado en otros sitios web. No hemos revisado, ni podemos revisar, todo el material, incluido el software informático, puesto a disposición pública a través de los sitios web y las páginas web a los que enlaza Oxoawards. Oxobox no dispone de ningún tipo de control sobre los sitios web y las páginas web que no sean de Oxobox y no es responsable de su contenido ni de su uso. Al enlazar a un sitio web o una página web que no sea de Oxoawards, Oxobox no declara ni insinúa que dé su respaldo a dicho sitio web o página web. Será responsabilidad tuya adoptar las precauciones necesarias para protegerte a ti mismo y a los sistemas de tu ordenador contra virus, gusanos, troyanos u otro contenido perjudicial o dañino. Oxobox rechaza cualquier tipo de responsabilidad por los posibles perjuicios resultantes del uso que hagas de sitios web y páginas web que no sean de Oxoawards.</span></p>
        <p>4.5. Infracción de derechos de autor. Del mismo modo que Oxobox solicita que se respeten sus derechos de propiedad intelectual, igualmente respeta los derechos de propiedad intelectual de otros. </span></p>
        <br>
        <p>Si crees que el material ubicado en Oxoawards o enlazado por Oxoawards infringe tus derechos de autor, te animamos a que se lo notifiques a Oxobox. Oxobox, en caso de que sea preciso o apropiado, procederá a la eliminación del material infractor o a la desactivación de todos los enlaces al material infractor. </span></p>
        <br>
        <p>Oxobox cancelará el acceso de usuario si, en las circunstancias apropiadas, dicho usuario está determinado a convertirse en un infractor continuado de los derechos de autor o de otros derechos de propiedad intelectual de Oxobox o de terceros. En caso de que se produzca esta cancelación, Oxobox no será responsable ni tendrá la obligación de reembolsar ninguna cantidad previamente pagada por dicho usuario.</span></p>
        <p>4.6. Propiedad intelectual. Este acuerdo no implica la transferencia entre Oxobox y el usuario (es decir, tú) de ninguna propiedad intelectual ni de Oxobox ni de ningún tercero y, por tanto, todos los derechos, títulos o intereses relativos a dicha propiedad permanecerán (como entre las partes) exclusivamente con Oxobox. Oxobox , Oxoawards, el logotipo de Oxobox &nbsp;y todas las demás marcas comerciales, marcas de servicio, gráficos y logotipos usados en relación con Oxobox son marcas comerciales o marcas comerciales registradas de Oxobox o de los otorgantes de licencias de Oxobox. Las demás marcas comerciales, marcas de servicio, gráficos y logotipos que se utilicen en relación con el sitio web pueden ser marcas comerciales de terceros. El uso que hagas del sitio web no te concede el derecho ni la licencia para reproducir o, de otro modo, utilizar ninguna de las marcas comerciales de Oxobox o de terceros.</span></p>
        <p>4.7. Anuncios. Oxobox se reserva el derecho de mostrar anuncios en tu cuenta de usuario, dependiendo ello del nivel de usuario en que te encuentres.</span></p>
        <p>4.8. Atribución. Oxobox se reserva el derecho de mostrar enlaces de atribución, como es el caso de “Entry en Oxoawards”, el autor del tema y la atribución de la fuente, nombre del festival, en el pie de página o en la barra de herramientas de tu interfaz de usuario. Independientemente de las mejoras adquiridas según sea tu nivel de usuario, los créditos del pie de página y la barra de herramientas de Oxoawards no se pueden modificar ni eliminar.</span></p>
        <br>
        <ol>
            <li><b>Otros.</b></span></p></li>
        </ol>
        <p>5.1. Cambios. Siempre estamos actualizando nuestros servicios, lo que significa que, a veces, tenemos que cambiar las condiciones legales por las que se rigen los servicios que ofrecemos. Si efectuamos cambios materiales, te los comunicaremos mediante una publicación en uno de nuestros blogs, o bien a través del envío de un mensaje correo electrónico o por medio de otra forma de comunicación antes de que entren en vigor dichos cambios. En dicho aviso se indicará un periodo razonable para que las nuevas condiciones entren en vigor. Si no estás de acuerdo con los cambios, debes dejar de usar Oxoawards antes de que finalice el periodo que se indica en el aviso. Si continúas usando Oxoawards , estarás sujeto a las nuevas condiciones. Sin embargo, cualquier conflicto que surja antes de que los cambios entren en vigor debe regirse por las condiciones (incluida la cláusula de arbitraje individual obligatoria) que estén vigentes en ese momento.</span></p>
        <p>5.2. Cancelación. Oxobox puede cancelar tu acceso a todo el sitio web o a parte de él en cualquier momento, con o sin motivo y con o sin aviso previo; dicha cancelación se hará efectiva inmediatamente. Si deseas cancelar este acuerdo o tu cuenta de Oxoawards &nbsp;(en caso de disponer de una), basta con que dejes de usar el sitio web. Todas las disposiciones de este acuerdo que, por su naturaleza, deban seguir siendo efectivas tras la cancelación, lo seguirán siendo, incluidas, entre otras, las disposiciones de propiedad, las exenciones de garantías, las indemnizaciones y las limitaciones de responsabilidad. </span></p>
        <p>5.3. Exención de garantías. El sitio web se ofrece “tal cual”. Por la presente, Oxobox, así como sus proveedores y otorgantes de licencia, renuncian a todas las garantías de cualquier tipo, de forma expresa o implícita, incluidas, entre otras, las garantías de aprovechamiento, de idoneidad para un propósito particular y de no contravención. Ni Oxobox ni sus proveedores u otorgantes de licencias garantizan que el sitio web esté libre de errores o que el acceso a él sea continuo o ininterrumpido. Si estás realmente leyendo esto, aquí hay una sorpresa. Entiendes que realizas descargas del sitio web, o que de otro modo obtienes contenido o servicios a través de él, por tu propia cuenta y riesgo.</span></p>
        <p>5.4. Limitación de responsabilidad. En ningún caso Oxobox o sus proveedores u otorgantes de licencias serán responsables de lo siguiente con respecto al objeto de este acuerdo bajo ningún tipo de contrato, negligencia, responsabilidad estricta u otra teoría legal o equitativa: (i) cualquier daño o perjuicio especial, incidental o derivado; (ii) el coste de la obtención de servicios o productos de sustitución; (iii) la interrupción del uso, o bien la pérdida o corrupción de los datos; o (iv) cualquier cantidad que exceda las tasas que hayas pagado a Oxobox de acuerdo con este acuerdo durante el periodo de doce (12) meses anterior a la causa del proceso. Oxobox no tendrá ninguna responsabilidad por los fallos o retrasos debidos a cuestiones que excedan su capacidad de control razonable. Lo precedente no se aplicará en la medida en que lo prohíban las leyes pertinentes.</span></p>
        <br>
        <ol>
            <li><b>Normas y Leyes aplicables.</b></span></p></li>
        </ol>
        <p>6.1. Garantía y representación generales. Declaras y garantizas que (i) el uso que hagas del sitio web se regirá de forma estricta por la Política de privacidad de Oxobox </span><span>(</span><a href='https://www.oxoawards.com/rules' target='_blank'><span>www.oxoawards.com/</span><a href='https://www.oxoawards.com/#/privacypolicy' target='_blank'><span>www.oxoawards.com/#/privacypolicy)</span></a></p>
        <br>
        <br>
        <p><span> por este acuerdo y por todas las leyes y normas pertinentes (incluidas, entre otras, las leyes o normas locales de tu país, estado, ciudad u otro departamento gubernamental referentes al contenido aceptable y a la conducta en línea) </span><span>,</span><span>y (ii) el uso que hagas del sitio web no infringirá ni se apropiará indebidamente de los derechos de propiedad intelectual de terceros.</span></p>
        <p><span>6.2. Indemnización. Aceptas indemnizar y eximir de responsabilidad a Oxobox, sus contratistas y sus otorgantes de licencias, así como a sus directores, directivos, empleados y agentes, contra cualquier tipo de demanda y gastos, incluidas las tasas legales, que puedan surgir del uso que hagas del sitio web, incluido, entre otros, el incumplimiento por tu parte de este acuerdo.</span></p>
        <p><span>6.3. Idioma. Estos términos y condiciones que por la presente aceptas se han escrito originalmente en español de Argentina. Puede que traduzcamos estas condiciones a otros idiomas. En caso de que surja un conflicto entre una versión traducida de estas condiciones del servicio y la versión en español, prevalecerá esta última.</span></p>
        <p><span>6.4. Miscelánea. Este acuerdo constituye el acuerdo total entre Oxobox y el usuario (es decir, tú) en lo referente al objeto del presente documento y solo se podrá modificar mediante una corrección escrita firmada por un ejecutivo autorizado de Oxobox, o bien a través de la publicación de una versión revisada por parte de Oxobox .</span></p>
        <p><span>6.5. El presente acuerdo, el acceso o uso del sitio web se regirá por las leyes de la República Argentina; asimismo, el lugar adecuado para resolver los conflictos que surjan a raíz de este acuerdo, el uso del sitio web o cualquier cuestión que se suscite que tenga relación con el uso de Oxoawards, aceptas la jurisdicción de los tribunales ordinarios de la Ciudad Autónoma de Buenos Aires, República Argentina.</span></p>
        <p><span>6.6. Puedes ceder los derechos que te otorga el presente acuerdo a cualquier parte, siempre que la misma acepte sus términos y condiciones y consienta en estar vinculado por ellos; Oxobox puede ceder los derechos que le otorga el presente acuerdo sin ninguna condición. El presente acuerdo será vinculante y redundará en beneficio de las partes, sus sucesores y los cesionarios autorizados.</span></p>"
);
