<?php

return array(
    "terms-and-conditions" => "<h1>OxoAwards Terms and Conditions</h1>
        <ol>
            <li><p><span><b>Definitions and Characteristics of the Service. </b></span></p></li>
        </ol>
        <p><span>1.1. Oxobox Awards Services (in future OxoAwards) is a software solution that facilitates the exchange of material between a participating user, an organizer and the jury of an awards festival.</span></p>
        <p><span>1.2. The flows of loading, data management and visualization through voting tools are limited to the group of users that responds to the organizer of the festival, who has all the management tools.</span></p>
        <p><span>1.3. The company Soluciones Oxo S.A. (hereinafter Oxobox), administrator of Oxoawards, is outside the use of the data that is published and for this reason they are external issues and cannot be claimed from Oxobox.</span></p>
        <p><span>1.4. Depending on the use that each user actually makes of the Oxoawards platform, they can be classified as participants, organizers, or simply general public.</span></p>
        <p><span>1.5. A participant is understood as a user who has registration credentials that allow them to appear at a convening festival, in order to show their contents for the purpose of being weighted.</span></p>
        <p><span>1.6 An organizer is understood as a user who has registration credentials that allow him to be the administrator of a festival. It is responsible for managing dates, criteria and conditions of the call. In case there are admission payment requirements to the festival participant, this organizing user is unequivocally responsible for the commercial management of the festival. </span></p>
        <p><span>1.7 The general public will be those users who do not have registration credentials, for which they only access as a viewer of those contents that the organizer makes available for public viewing.</span></p>
        <br>
        <ol>
            <li><p><span><b>Terms of service.</b></span></p></li>
        </ol>
        <p><span>The following terms and conditions govern any use of Oxoawards and all content, services and products available on the system.</span></p>
        <p><span>Please read this agreement carefully before accessing or using Oxoawards. By accessing or using any part of Oxoawards, you agree to be bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, you may not access Oxoawards or use any of the services. If these terms and conditions are considered an offer from Oxobox, your acceptance is expressly limited to those conditions.</span></p>
        <br>
        <p><span>2.1. Oxobox provides its award festival hosting service for audiovisual content called Oxoawards, and we would love for you to use it. Oxobox and Oxoawards are free services for participating users and the general public,</span><span> </span><span>regardless of what each sponsored festival -organizing user- decides to charge for participation in it .</span></p>
        <p><span>2.2. Our service is designed to give you as much control and ownership over what happens to your site as possible, and to encourage you to freely express yourself as you are. However, you must be responsible for what you post. In particular, make sure that none of the prohibited items (such as spam, viruses, or serious threats of violence) appear on your site and that your site does not include any links to them.</span></p>
        <br>
        <p><span>2.3. If you find a festival on Oxoawards that you believe violates our Terms of Service, please visit our Report and Dispute Resolution page. </span><span>www.oxoawards.com/rules</a>)</span></p>
        <br>
        <p><span>2.4. By granting your acceptance of the terms and conditions, the website is offered without modification of all the terms and conditions cited herein and all rules, policies (including, without limitation, the Oxoawards Privacy Policy </span><span> (</span><a href='https://www.oxoawards.com/#/privacypolicy' target='_blank'><span>www.oxoawards.com/#/privacypolicy)</span></a><span> and operating procedures that Oxoawards may publish from time to time on this site (collectively, the “agreement”) .</span></p>
        <p><span>2.5. By accepting the agreement, you are doing so with Oxobox.</span></p>
        <p><span>2.6. The Website is not directed to children under the age of 13 and the Website service is only offered to users over the age of 13. You must not register to use the Website if you are under 13 years of age. Any person who registers as a user or who provides their personal information to the website declares that they are over 13 years of age.</span></p>
        <p><span>2.7. Your Oxoawards account. </span></p>
        <ul>
            <li>If you create an Oxoawards entry, also called an Entry, you will be responsible for maintaining the security of your account; In addition, you will be entirely responsible for all activities that take place with that account and for any other action that takes place in relation to the Oxoawards.</span></p></li>
            <li>You must not describe or assign keywords to your Entry</span><span> </span><span>in a way that is illegal, misleading or designed to exploit the name or reputation of others; Likewise, Oxobox may change or eliminate any description or keyword that it considers inappropriate, illegal or that, in another way, may cause damage to third parties.</span></p></li>
            <li>You must immediately notify Oxobox </span><span>(</span>info@oxobox.tv<span> </span><span>of any use unauthorized access to your account, as well as any other breach of security. Oxobox will not be responsible for any of your acts or omissions, including damages of any kind derived from said acts or omissions.</span></p></li>
        </ul>
        <p>2.8. Responsibility of Oxoawards users.</span></p>
        <ul>
            <li>If you run a festival, comment, post material to Oxoawards, post Oxoawards links on websites, or otherwise make material publicly available (or allow a third party to do so) through Oxoawards (this type of material is called content), you will be entirely responsible for the content and the possible damages that said content may cause. This is regardless of the form the content takes, including but not limited to text, photos, video, audio, or code. By making content publicly available, you represent and warrant that the content does not violate this agreement.</span></p></li>
            <li>By submitting content to Oxoawards for inclusion in your user profile, you grant Oxobox a non-exclusive, royalty-free, worldwide license to reproduce, modify, adapt and publish the content for the sole purpose of displaying, distributing and promoting your content. content. This license allows Oxobox to make published content available to third parties selected by Oxobox so that such third parties may analyze and distribute (but not publicly display) this content through their services.</span></p></li>
            <li>If you remove any content, Oxobox will use all reasonable means to remove it from the website, but you acknowledge that caching or references to the content will not be immediately unavailable.</span></p></ li>
            <li>Without limiting those representations or warranties, Oxobox has the right (but not the obligation), in Oxobox's sole discretion, to (i) reject or remove any content that, in its reasonable opinion, violates Oxobox's policies or that is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any person or entity for any reason in Oxobox's sole discretion. Oxobox will have no obligation to refund any amount previously paid.</span></p></li>
        </ul>
        <br>
        <ol>
            <li><span><b>Payments and renewal. </b></span></p></li>
        </ol>
        <p>3.1. General conditions. </span></p>
        <p>As determined in point 2.1. hereof, Oxoawards is a service free of charge for participating users and the general public, without prejudice to what each organizing user decides to charge them.</span></p>
        <p>Oxobox has no connection with the payment options that each organizing user includes in its interface, and therefore, is exempt from any liability arising from said operation, its modification and/or conditions and/or cancellation.</p>
        <p>In the event that, as a participating user, you intend to cancel access to the Festival at any time, and attempt said cancellation using the Oxoawards interface, it will only send a courtesy notification to the organizer, not Oxobox being neither obliged nor responsible for the result thereof.</span></p>
        <p>If any, the terms of reimbursement are the exclusive power of the organizer, &nbsp;and Oxobox does not mediate in the resolution of conflicts that may exist between participants and the organizer of a festival. </span></p>
        <br>
        <p><span>3.2. However, if your user level is an organizer, optional paid services may be available, such as subscription payments, additional storage or domain purchases (any of these services are called “upgrades”). When you select an upgrade, you agree to pay Oxobox the indicated monthly or annual subscription fees for such service. Payments will be charged prepaid on the day you sign up for an upgrade and will cover the use of that service for a monthly or annual subscription period, as applicable. Upgrade fees will not be refunded.</span></p>
        <br>
        <ol>
            <li><b>Content. Restricted use. </b></span></p></li>
        </ol>
        <p>4.1. You must not use Oxoawards to materially copy products or services offered by Oxobox, including republishing Oxoawards content. If Oxobox believes, in its sole discretion, that you have violated or attempted to violate these terms or the spirit of these terms, your ability to use and access Oxoawards may be temporarily or permanently revoked, with or without notice.</span> </p>
        <p>4.2. Responsibilities of Website Visitors. Oxobox has not reviewed, and cannot review, all of the material, including computer software, posted on the Website; cannot, therefore, be responsible for the content, use or effects of said material. By operating the website, Oxobox does not state or imply that it endorses the posted material or that it believes such material is appropriate, useful, or not harmful. It is your responsibility to take precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, or other harmful or harmful content. 4.3. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content that includes technical inaccuracies, typographical errors, or other flaws. The Website may also contain material that violates the rights of privacy or publicity, or infringes the intellectual property rights or other proprietary rights of others; the downloading, copying or use of such material may also be subject to additional terms and conditions, expressed or not. Oxobox rejects any responsibility for damages resulting from the use made by users of the website or from the downloads made by said visitors of the published content. </span></p>
        <p>4.4. Content Posted on Other Websites. We have not reviewed, and cannot review, all of the material, including computer software, made publicly available through the websites and web pages to which Oxoawards links. Oxobox has no control over non-Oxobox websites and web pages and is not responsible for their content or use. By linking to a non-Oxoawards website or web page, Oxobox does not represent or imply that it endorses such website or web page. It is your responsibility to take precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, or other harmful or harmful content. Oxobox rejects any type of responsibility for possible damages resulting from the use you make of websites and web pages that are not Oxoawards.</span></p>
        <p>4.5. Copyright infringement. Just as Oxobox requests that its intellectual property rights be respected, it also respects the intellectual property rights of others. </span></p>
        <br>
        <p>If you believe that material located on Oxoawards or linked by Oxoawards infringes your copyright, we encourage you to notify Oxobox. Oxobox, if necessary or appropriate, will remove the infringing material or disable all links to the infringing material. </span></p>
        <br>
        <p>Oxobox will terminate a user's access if, under appropriate circumstances, such user is determined to become a continuing infringer of the copyrights or other intellectual property rights of Oxobox or third parties. In the event of this cancellation, Oxobox will not be responsible or have the obligation to reimburse any amount previously paid by said user.</span></p>
        <p>4.6. Intellectual property. This agreement does not imply the transfer between Oxobox and the user (that is, you) of any intellectual property neither of Oxobox nor of any third party and, therefore, all the right, title or interest relative to said property will remain (as between the parties). ) exclusively with Oxobox. Oxobox , Oxoawards, the Oxobox logo &nbsp;and all other trademarks, service marks, graphics and logos used in connection with Oxobox are trademarks or registered trademarks of Oxobox or Oxobox's licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of others. Your use of the website does not grant you the right or license to reproduce or otherwise use any Oxobox or third party trademarks.</span></p>
        <p>4.7. Advertisements. Oxobox reserves the right to display advertisements in your user account, depending on the user level you are at.</span></p>
        <p>4.8. Attribution. Oxobox reserves the right to display attribution links, such as “Entry in Oxoawards”, theme author and source attribution, festival name, in the footer or toolbar of your user interface. Regardless of upgrades purchased based on your user level, Oxoawards toolbar and footer credits cannot be modified or removed.</span></p>
        <br>
        <ol>
            <li><b>Others.</b></span></p></li>
        </ol>
        <p>5.1. Changes. We are always updating our services, which means that sometimes we have to change the legal conditions that govern the services we offer. If we make material changes, we will notify you by posting on one of our blogs, or by sending you an email or other form of communication prior to the changes becoming effective. Said notice will indicate a reasonable period for the new conditions to take effect. If you do not agree to the changes, you must stop using Oxoawards before the end of the period indicated in the notice. If you continue to use Oxoawards, you will be bound by the new conditions. However, any dispute that arises before the changes take effect must be governed by the terms (including the mandatory individual arbitration clause) that are in effect at that time.</span></p>
        <p>5.2. Cancellation. Oxobox may terminate your access to all or part of the Website at any time, with or without reason and with or without notice; such cancellation will be effective immediately. If you wish to cancel this agreement or your Oxoawards account &nbsp;(if you have one), simply stop using the website. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, but not limited to, ownership provisions, disclaimers of warranties, indemnities, and limitations of liability. </span></p>
        <p>5.3. Disclaimer of warranties. The website is provided “as is”. Oxobox, as well as its suppliers and licensors, hereby disclaim all warranties of any kind, express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, and non-infringement. . Neither Oxobox nor its suppliers or licensors warrant that the website will be error-free or that access to it will be continuous or uninterrupted. If you're really reading this, here's a surprise. You understand that you download from, or otherwise obtain content or services through, the Website at your own risk.</span></p>
        <p>5.4. Limitation of Liability. In no event shall Oxobox or its suppliers or licensors be liable for the following with respect to the subject matter of this agreement under any contract, negligence, strict liability, or other legal or equitable theory: (i) any special, incidental or consequential damages or derivative; (ii) the cost of obtaining replacement products or services; (iii) interruption of use, or loss or corruption of data; or (iv) any amount that exceeds the fees that you have paid to Oxobox in accordance with this agreement during the period of twelve (12) months prior to the cause of the process. Oxobox shall have no liability for failures or delays due to matters beyond its reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</span></p>
        <p>5.4. Limitation of Liability. In no event shall Oxobox or its suppliers or licensors be liable for the following with respect to the subject matter of this agreement under any contract, negligence, strict liability, or other legal or equitable theory: (i) any special, incidental or consequential damages or derivative; (ii) the cost of obtaining replacement products or services; (iii) interruption of use, or loss or corruption of data; or (iv) any amount that exceeds the fees that you have paid to Oxobox in accordance with this agreement during the period of twelve (12) months prior to the cause of the process. Oxobox shall have no liability for failures or delays due to matters beyond its reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</span></p>
        <br>
        <ol>
            <li><b>Applicable Rules and Laws.</b></span></p></li>
        </ol>
        <p>6.1. General Warranty and Representation. You represent and warrant that (i) your use of the website will be strictly governed by the Oxobox Privacy Policy </span><span>(</span><a href='https://www.oxoawards.com/#/privacypolicy' target='_blank'><span>www.oxoawards.com/#/privacypolicy)</span></a></p>
        <br>
        <br>
        <p><span> by this agreement and by all applicable laws and regulations (including, without limitation, the local laws or regulations of your country, state, city or other government department regarding acceptable content and online conduct)<span>,</span><span>and (ii) your use of the website will not infringe or misappropriate the intellectual property rights of third parties.</span></p>
        <p><span>6.2. Compensation. You agree to indemnify and hold harmless Oxobox, its contractors and licensors, as well as their directors, officers, employees and agents, against any and all claims and expenses, including legal fees, that may arise from your use of the website, including, without limitation, your breach of this agreement.</span></p>
        <p><span>6.3. Idiom. These terms and conditions that you hereby accept have been originally written in Argentine Spanish. We may translate these terms into other languages. In the event of a conflict between a translated version of these Terms of Service and the Spanish version, the Spanish version shall prevail.</span></p>
        <p><span>6.4. Miscellany. This agreement constitutes the entire agreement between Oxobox and the user (that is, you) in relation to the subject matter of this document and can only be modified by means of a written correction signed by an authorized executive of Oxobox, or through the publication of a revised version by Oxobox .</span></p>
        <p><span>6.5. This agreement, access or use of the website will be governed by the laws of the Argentine Republic; Likewise, the appropriate place to resolve conflicts that arise as a result of this agreement, the use of the website or any issue that may arise that is related to the use of Oxoawards, you accept the jurisdiction of the ordinary courts of the Autonomous City of Buenos Aires Aires, Argentine Republic.</span></p>
        <p><span>6.6. You may assign your rights under this agreement to any party, provided that the party accepts its terms and conditions and agrees to be bound by them; Oxobox may assign the rights granted by this agreement without any conditions. This agreement will be binding on and will inure to the benefit of the parties, their successors and authorized assigns.</span></p>"
);

